// staticDeals.ts
export const staticDeals = [
  {
    id: "deal-0",
    title: "DJERBA(DJE) ✈︎ GENEVA(GVA)",
    image: "https://static.tunisair.com/uploads/destinations/GVA.jpg",
    price: 459500,
    lastDate: "30 August 2025",
    type: "Round-Trip",
    month: "August",
    region: "Europe",
  },
  {
    id: "deal-1",
    title: "DJERBA(DJE) ✈︎ NICE(NCE)",
    image: "https://static.tunisair.com/uploads/destinations/NCE.jpg",
    price: 617500,
    lastDate: "30 August 2025",
    type: "Round-Trip",
    month: "August",
    region: "Europe",
  },
  {
    id: "deal-2",
    title: "DJERBA(DJE) ✈︎ MUNICH(MUC)",
    image: "https://static.tunisair.com/uploads/destinations/MUC.jpg",
    price: 650500,
    lastDate: "31 August 2025",
    type: "Round-Trip",
    month: "August",
    region: "Europe",
  },
  {
    id: "deal-3",
    title: "DJERBA(DJE) ✈︎ LYON(LYS)",
    image: "https://static.tunisair.com/uploads/destinations/LYS.jpg",
    price: 600000,
    lastDate: "15 June 2025",
    type: "Round-Trip",
    month: "June",
    region: "Europe",
  },
  {
    id: "deal-4",
    title: "DJERBA(DJE) ✈︎ MARSEILLE(MRS)",
    image: "https://static.tunisair.com/uploads/destinations/MRS.jpg",
    price: 520500,
    lastDate: "10 June 2025",
    type: "Round-Trip",
    month: "June",
    region: "Europe",
  },
  {
    id: "deal-5",
    title: "DJERBA(DJE) ✈︎ PARIS(ORY)",
    image: "https://static.tunisair.com/uploads/destinations/ORY.jpg",
    price: 494500,
    lastDate: "20 June 2025",
    type: "Round-Trip",
    month: "June",
    region: "Europe",
  },
  {
    id: "deal-6",
    title: "DJERBA(DJE) ✈︎ FRANKFURT(FRA)",
    image: "https://static.tunisair.com/uploads/destinations/FRA.jpg",
    price: 1102500,
    lastDate: "05 July 2025",
    type: "Round-Trip",
    month: "July",
    region: "Europe",
  },
  {
    id: "deal-7",
    title: "MONASTIR(MIR) ✈︎ MARSEILLE(MRS)",
    image: "https://static.tunisair.com/uploads/destinations/MRS.jpg",
    price: 487500,
    lastDate: "12 July 2025",
    type: "Round-Trip",
    month: "July",
    region: "Europe",
  },
  {
    id: "deal-8",
    title: "MONASTIR(MIR) ✈︎ MUNICH(MUC)",
    image: "https://static.tunisair.com/uploads/destinations/MUC.jpg",
    price: 691500,
    lastDate: "18 July 2025",
    type: "Round-Trip",
    month: "July",
    region: "Europe",
  },
  {
    id: "deal-9",
    title: "MONASTIR(MIR) ✈︎ LYON(LYS)",
    image: "https://static.tunisair.com/uploads/destinations/LYS.jpg",
    price: 487000,
    lastDate: "25 August 2025",
    type: "Round-Trip",
    month: "August",
    region: "Europe",
  },
  {
    id: "deal-10",
    title: "MONASTIR(MIR) ✈︎ NICE(NCE)",
    image: "https://static.tunisair.com/uploads/destinations/NCE.jpg",
    price: 580500,
    lastDate: "28 August 2025",
    type: "Round-Trip",
    month: "August",
    region: "Europe",
  },
  {
    id: "deal-11",
    title: "MONASTIR(MIR) ✈︎ PARIS(CDG)",
    image: "https://static.tunisair.com/uploads/destinations/default_image.jpg",
    price: 494500,
    lastDate: "02 July 2025",
    type: "Round-Trip",
    month: "July",
    region: "Europe",
  },
];